### ISSUE TITLE
Documenter le cycle d'une release

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/prestashop-retro#13]
Manque de clarté sur le fonctionnement d'une release : beta, RC, etc.

https://docs.google.com/document/d/1E52P85KZs8x2eTYlsGAoagYIIhnvyhuJ6lIaQ8_7J3Q/edit?usp=sharing

- [x] add to the devdocs
- [x] write an article 
- [x] publish article

**Comment by matks** [comment]
This topic is done
- article about [Minor releases lifecycle](https://build.prestashop.com/news/ps17-minor-release-lifecycle/)
- article about [Patch releases lifecyle](https://build.prestashop.com/news/ps17-patch-release-lifecycle/)
- the content has been moved [into devdocs](https://devdocs.prestashop.com/1.7/release/) (PR https://github.com/PrestaShop/docs/pull/524)
