### ISSUE TITLE
Pouvoir publier / recommander des modules gratuits

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestashop-retro#26]
Sur Addons ? Sur un site dédié ? Avec un CMS ? Avec un PrestaShop ?

Le débat est ouvert.

**Comment by Progi1984** [comment]
Je vais rouvrir ce ticket suite à une information que m'a remonté @Quetzacoalt91 : les modules gratuits existent déjà sur Addons. Voici un exemple : 
https://addons.prestashop.com/en/data-migration-backup/5496-1-click-upgrade.html

![image](https://user-images.githubusercontent.com/1533248/83043637-64a4db00-a043-11ea-86a0-ec1807af7338.png)

**Comment by ttoine** [comment]
c'est un sujet touchy. par le passé, les modules "gratuits" étaient listés sur Addons, mais ont été enlevé car ils consommaient beaucoup de ressources et étaient considérés comme masquant les modules payant. un frein pour le business, quoi.
dans un contexte différent, wordpress.org ou drupal.org font ça très bien et ne vendent rien.
donc, peut-être que nous devrions aussi faire ça sur un prestashop.org.

**Comment by Progi1984** [comment]
> c'est un sujet touchy. par le passé, les modules "gratuits" étaient listés sur Addons, mais ont été enlevé car ils consommaient beaucoup de ressources et étaient considérés comme masquant les modules payant. un frein pour le business, quoi.
> dans un contexte différent, wordpress.org ou drupal.org font ça très bien et ne vendent rien.
> donc, peut-être que nous devrions aussi faire ça sur un prestashop.org.

Et fournir un MBO vers ce prestashop.org

**Comment by ttoine** [comment]
disons que ça ferait sens dans le cadre d'un projet open source indépendant de l'entreprise et sur un .org, puisque c'est ce que font les autres CMS ou logiciels libres équivalents.

ainsi, la version disponible sur le .com serait augmentée avec le MBO d'Addons, et les autres services en fonction des zones géographiques.

**Comment by ttoine** [comment]
ça permettrait aussi de réfléchir, tant qu'à faire, à utiliser PrestaShop pour faire prestashop.org et l'utiliser en mode catalogue.
