### ISSUE TITLE
Issuebot project for a better team work and efficiency

### ISSUE THREAD

**Issue by PierreRambaud** [PrestaShop/prestashop-retro#38]
This project aims at automatizing a certain number of tasks that are done manually today  : 
- move issues in their kanban according to the status of their pull requests
- synchronise status of issues which are in different kanbans
- add labels to issues and PR according to their status

The issuebot project uses Probot.

**Comment by colinegin** [comment]
Attention le travail de probot par Ibrahima est différent de celui nécessaire sur Prestonbot permettant de forcer l'association d'une PR à une issue.

**Comment by colinegin** [comment]
@sowbiba can you confirm I can close this issue as issuebot is now in production ? 
Is there a new batch of improvements to come ?

**Comment by LouiseBonnard** [comment]
@sowbiba, can I close this ticket?
