### ISSUE TITLE
Automated Github maxi kanban 

### ISSUE THREAD

**Issue by PierreRambaud** [PrestaShop/prestashop-retro#40]
We need a new tool to centralize the display of all kanbans ( 1.7.X, modules, Side projects, etc.), to ensure a better team productivity and "ressource allocation".

To do so we need to use what has already been done with issuebot.

**Comment by eternoendless** [comment]
On fera un maxi kanban sur github, automatisé via probot / issuebot

**Comment by colinegin** [comment]
Waiting for issuebot to be released.

Update : Issuebot is now in production !

**Comment by LouiseBonnard** [comment]
@sowbiba, what's the status of this ticket?
