### ISSUE TITLE
PostMortem Faille PHPUnit

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/prestashop-retro#53]
- [x] PostMortem meeting
- [x] Write the report of the meeting
- [x] Write the article detailing the postmortem
- [x] Publish the article

**Comment by eternoendless** [comment]
Document done, should post a blog article

**Comment by eternoendless** [comment]
Blog post here: https://github.com/PrestaShop/prestashop.github.io/pull/641

**Comment by colinegin** [comment]
I get we can close this issue, congrats ;)
