### ISSUE TITLE
Synchroniser les process de release produit et dév pour les patchs

### ISSUE THREAD

**Issue by sam-pires** [PrestaShop/prestashop-retro#56]
Lors de la release d'un patch, du contenu doit être préparé côté Produit.

Contenus:
- Release Note sur Build
- Email pour annoncer la release aux agences et dévs
- Contenu pour la NL B2B suivante

Ce contenu est basé sur le changelog qui doit être fourni par le release manager tech.
Le release manager tech est aussi reviewer du contenu.

Pour éviter toute friction dans le process, partageons nos process respectifs et synchronisons les 💪

- [x] Côté PM regarder la todo des devs sur Confluence 

Selon

- [x] Ajouter une action pour indiquer au Release Manager Tech à quel moment 

et/ou

- [x] Ajouter du contexte Produit pour que le dév est de la visibilité sur les actions côté produit

Enfin
- [x] Ajouter du contexte dans la todo Produit par rapport aux action côté dévs

**Comment by NeOMakinG** [comment]
Ping @sam-pires @Progi1984
