### ISSUE TITLE
Setup ProductBoard's Portal for PrestaShop Core 👨‍🏫

### ISSUE THREAD

**Issue by sam-pires** [PrestaShop/prestashop-retro#60]
### April 2020
- [x] Replace « TEAM PRODUIT » by « CORE PRODUCT TEAM »
- [x] In the BO PB, create features corresponding to what has been done in the 1.7.6 -> Focus on the content for Portal -> put them in « Done » status once ready to remove them from the features' list
- [x] In the BO PB create features corresponding to to what has been done in the 1.7.7
- [x] ONCE THE FEATURES READY Create the tabs
- [x]  Tab 1 - Under consideration
    - [x]  Productivity
    - [x]  Growth
    - [x]  International
    - [x]  Flexibility
- [x]  Tab 2 - In progress
    - [x]  User research
    - [x]  Design
    - [x]  Specifications
    - [x]  Dev
    - [x]  Testing 
- [x]  Tab 3 - Coming in the next release
- [x]  Tab 4 - Launched
    - [x]  1.7.5
    - [x]  1.7.6
- [x]  Create the status "Ready for next version"
- [x] Write a Build blog to explain "how to" use PB Portal and the process on our side

- [x] Create email for the User Club + link to "how to article"
- [x] Create email for ppl who subscribed on Portal + link to "how to" article

#### After a couple of days
- [x] Open ideas submission
- [x] Send emails to User Club and Subscribers

### TBC
- [ ] Add some visits analytics tool (if not possible through PB)
    - [ ] If not possible through PB, embed the portal on a website where we can set up analytics
- [ ] Add link to the Portal in prestashop.com's footer - Warning: if other teams at PS use PB, we should create different Portals to differentiate the 2 roadmaps (OD project, company products)
- [ ] Add link to feedback.prestashop.com in PrestaShop 1.7's BO
- [ ] Share the info in the Core Weekly
- [ ] Share the info in the Crowdin Monthly
- [x] Share the info in the general Newsletter 
- [x] Share the info in the B2B Newsletter

**Comment by colinegin** [comment]
@sam-pires FYI i've put this project in the side project kanban

**Comment by LouiseBonnard** [comment]
@PrestaShop/product-team for the follow-up. ;-)

**Comment by sam-pires** [comment]
😢
