### ISSUE TITLE
Interview contributors from the PrestaShop community

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/prestashop-retro#64]
Make a series of interviews to chat with various community members and learn from their experience as contributors. Idea behind is to make their needs meet ours and better collaborate all together.

## What has been done?

- [x] GitHub contributor Adib A.
- [x] PS open source evangelist Antoine T.
- [x] Agency director Jean-François V.
- [x] PS core developer Mathieu F.
- [x] GitHub contributor Tanguy S.
- [x] GitHub contributor David G.
- [x] Partner agency 202 ecommerce
- [x] PS core developer Pierre R.
- [x] GitHub contributor Rodrigo L.
- [x] GitHub contributor Pululu K.

## What is considered to keep on learning:

GitHub contributor Konrad P.
GitHub contributor gadnis
GitHub contributor Hlavtox
GitHub contributor maofree

🐣 🐥 More to come, stay tuned!

**Comment by colinegin** [comment]
@LouiseBonnard will this project require dev time ? I guess it's more your recommendations after all interviews which will need dev time ?
