### ISSUE TITLE
Develop our use of the good first issue label

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/prestashop-retro#68]
Earlier that year, the PrestaShop team decided to use new leverage to help new contributors participate in the PrestaShop project on GitHub: the _good first issue_ label. See [list](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22). 

So we need a document to gather all questions it raises (from both the internal teams and the community contributors) and therefore better define what does the label means and how it should be used. Here are some actions to promote it, internally as well as externally:

- [x] Create the FAQ document, available [here](https://docs.google.com/document/d/1OwwoyK41DtMMLRh_HFF-f65tI782StRnT-ZQHgfvAeY/edit)
- [x] Publish it on the Build devblog + share in the open source Slack
- [x] Add GFI to the README #[18553](https://github.com/PrestaShop/PrestaShop/issues/18553)
- [x] Add GFI to the contribution guidelines
- [x] Add GFI to the devdocs
- [x] Add GFI to [MunGell](MunGell/awesome-for-beginners#635)
- [ ] Improve the [CodeTriage](https://www.codetriage.com/prestashop/prestashop) selection to make it pick GFI as a priority

**Comment by ttoine** [comment]
Information to display maybe on:

- readme
- contribution guidelines
- devdocs

**Comment by NeOMakinG** [comment]
https://github.com/MunGell/awesome-for-beginners/pull/635

Leaving this here, so we can follow how it evolute
