### ISSUE TITLE
Candidates for side project board

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestashop-retro#71]
Hi @LouiseBonnard @colinegin I missed the retro where the Side Projects board was decided so I'm sorry if this post is irrelevant.

Here is a list of side-projects I have in mind, I dont know whether they are valid, approved, and should go into the board ?

- Full automatization of the generation of the Core Weekly blog posts (currenty it's 50% automatic)
- Rework the structure of the developer documentation
_The developer documentation has grown huge over years and now some sections are big while others are small. There is a lack of balance, some content is duplicated, other similar content should be regrouped. Also some content is now outdated because it was written years ago and now we have more up-to-date practices._
- Write a proper documentation for PrestaShop webservices structure and usage
- Provide a SDK for PrestaShop webservices usage (PHP or JS)
- Provide a benchmark and documentation about PrestaShop scaling (basically: "if I have a catalog with X products, Y categories, how big should be my server ?")
- [Provide an automated build tool for github ZIP archives](https://github.com/PrestaShop/PrestaShop/issues/17044)
- [Plug in a linter for templates](https://github.com/PrestaShop/PrestaShop/issues/14146) (this one might go into PS 1.7.X project one day, but not sure)
- [Provide a tool to easily build/deploy a shop from PrestaShop source code](https://github.com/PrestaShop/PrestaShop/issues/14086)
- [Provide example modules for all kind of modules](https://github.com/PrestaShop/PrestaShop/issues/14005) such as carrier module, payment module, cart module ...

**Comment by LouiseBonnard** [comment]
Hi @matks, no worries! We're moving all issues from this prestashop-retro project to [this one](https://github.com/orgs/PrestaShop/projects/6), please add all ideas to the board so that they can be studied and validated. :-)

**Comment by ttoine** [comment]
Brilliant ideas :-)

**Comment by colinegin** [comment]
All ideas should be put in the backlog (as detailed as possible) and then we'll be able to discuss about them and see how relevant they are and what is their level of priority !
