### ISSUE TITLE
Identify Hacktoberfest contributions

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/prestashop-retro#80]
As discussed with @eternoendless, in order to better identify the Hacktoberfest contributions during October, it'd be nice to add a checkbox to the message Prestonbot posts when a pull request is created. It could contain the following question: _Is this contribution part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) challenge?_ 

I have created a dedicated label right here: https://github.com/PrestaShop/PrestaShop/labels/Hacktoberfest

**Comment by eternoendless** [comment]
I thought about it and I realized that a checkbox is not an option because the contributor wouldn't be able to check it (because it doesn't have the permissions to edit another user's comment)

**Comment by LouiseBonnard** [comment]
Unfortunately, I can't figure out any quick solution... I suggest 1/ editing the PR template even though it is not as reliable as expected or 2/ simply letting the contributor mention the Hacktoberfest challenge in the PR description (this way, maintainers would be able to add the dedicated label by themselves). I know it is not ideal. :-(
